name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
    
      - name: Copy project files to EC2
        run: |
          rsync -avz --exclude '.git' ./ ubuntu@${{ secrets.EC2_HOST_IP }}:/home/ubuntu/docker_project

      - name: Docker stop and rm
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/docker_project &&
          docker-compose down &&
          docker rm -f $(docker ps -aq)
          "

  
      - name: Deploy with Docker Compose
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "
          cd /home/ubuntu/docker_project &&         
          docker-compose up -d --build
          "
