name: Deploy to EC2 using Docker Compose

on:
  push:
    branches:
      -main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
       
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
           ssh-private-key: ${{secrets.SSH_TOKEN}}

      - name: Copy project files to EC2
        run: |
          rsync -avz --exclude '.git' ./ubuntu@${{EC2_HOST_IP}}:/home/unbuntu/docker_project

      - name: Docker Compose down and rm
        run: |
          ssh ubuntu@${{EC2_HOST_IP}}:/home/unbuntu/docker_project "
          cd /home/ubuntu/docker_project &&
          docker-compose down &&
          docker rm $(docker ps -aq)
          "

      - name: Docker Compose up
        run: |
          ssh ubuntu@${{EC2_HOST_IP}}:/home/unbuntu/docker_project "
          cd /home/ubuntu/docker_project &&        
          docker-compose up -d --build
          "
        
